---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: ubuntu-1804-ruby-dev-virtualbox
    driver:
      box: ubuntu-1804-ruby-dev-virtualbox-test
      box_url: file:///<%= ENV['PWD'] %>/output-ubuntu-1804-ruby-dev/package.box
      provider: virtualbox

verifier:
  name: inspec
  sudo: false

suites:
  - name: default
